backend:
  name: git-gateway
  branch: main

media_folder: 'public/uploads'
public_folder: '/uploads'

local_backend: true

collections:
  - name: 'news'
    label: 'Новини'
    folder: 'src/content/news'
    slug: '{{fields.generatedSlug}}'
    summary: '{{title}}'
    identifier_field: 'generatedSlug'
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - {
          label: 'Дата',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
        }
      - { label: 'Короткий опис новини', name: 'description', widget: 'string' }
      - { label: 'Текст новини', name: 'body', widget: 'markdown' }
      - { name: 'generatedSlug', widget: 'hidden', default: 'slug' }
  - name: 'lessons'
    label: 'Уроки'
    folder: 'src/content/lessons'
    slug: '{{fields.generatedSlug}}'
    identifier_field: 'generatedSlug'
    summary: '{{title}}'
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - {
          label: 'Дата',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
        }
      - { label: 'Короткий опис уроку', name: 'description', widget: 'string' }
      - { label: 'Текст уроку', name: 'body', widget: 'markdown' }
      - { name: 'generatedSlug', widget: 'hidden', default: 'slug' }
  - name: 'stories'
    label: 'Розповіді'
    folder: 'src/content/stories'
    slug: '{{fields.generatedSlug}}'
    summary: '{{title}}'
    identifier_field: 'generatedSlug'
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - {
          label: 'Дата',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
        }
      - {
          label: 'Короткий опис розповіді',
          name: 'description',
          widget: 'string',
        }
      - { label: 'Текст розповіді', name: 'body', widget: 'markdown' }
      - { name: 'generatedSlug', widget: 'hidden', default: 'slug' }
  - name: 'figures'
    label: 'Історичні постаті'
    folder: 'src/content/figures'
    slug: '{{fields.generatedSlug}}'
    identifier_field: 'generatedSlug'
    summary: '{{title}}'
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - {
          label: 'Дата',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
        }
      - { label: 'Короткий опис статті', name: 'description', widget: 'string' }
      - { label: 'Текст статті', name: 'body', widget: 'markdown' }
      - { name: 'generatedSlug', widget: 'hidden', default: 'slug' }
