backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/images"

collections:
  - name: "news"
    label: "Новини"
    folder: "src/news"
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Короткий опис новини", name: "description", widget: "string"}
      - {label: "Текст новини", name: "body", widget: "markdown"}
  - name: "lessons"
    label: "Уроки"
    folder: "src/lessons"
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Короткий опис уроку", name: "description", widget: "string"}
      - {label: "Текст уроку", name: "body", widget: "markdown"}
  - name: "stories"
    label: "Розповіді"
    folder: "src/stories"
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Короткий опис розповіді", name: "description", widget: "string"}
      - {label: "Текст розповіді", name: "body", widget: "markdown"}
  - name: "figures"
    label: "Історичні постаті"
    folder: "src/figures"
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Короткий опис статті", name: "description", widget: "string"}
      - {label: "Текст статті", name: "body", widget: "markdown"}